services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
    # Je crée le bind pour le reload
      - type: bind
        source: ./client
        target: /home/node
      # Je crée le volume pour les node_modules
      - type: volume
        target: /home/node/node_modules
    stdin_open: true
    tty: true
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - type: bind
        source: ./api/src
        target: /app/src
    ports:
      - "3001:80"
  db:
    image: mongo
    restart: always
    volumes:
      - type: volume
        source: dbtest
        target: /data/db
    ports:
      - "27017:27017"
  reverse-proxy:
    build: 
      context: ./reverse-proxy
      dockerfile: Dockerfile.dev
    ports: 
      - "80:80"
    depends_on:
      - client
      - api
      - db
# déclaration du volume
volumes:
  dbtest: