services: 
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    depends_on:
      - api
      - db
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.prod
    #env_file:
      #- ./api/.env
    environment:
      - MONGO_USERNAME
      - MONGO_PWD
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - type: volume
        source: dbprod
        target: /data/db
    #env_file:
      #- ./db/.env
    # à lancer seulement la 1ère fois lors de l'initilisation de la base de données
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    restart: unless-stopped
  reverse-proxy:
    build: 
      context: ./reverse-proxy
      dockerfile: Dockerfile.prod
    ports:
    # port http
      - "80:80"
    # port https
      - "443:443"
    volumes:
      - type: bind
      # path certificat TLS sur le VPS
        source: /etc/letsencrypt
      # copie dans le empl dans le container
        target: /etc/letsencrypt
    restart: unless-stopped
    depends_on:
      - api
      - db
      - client
volumes:
  dbprod:
    external: true
